- name: Download kubectl
 get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.22.0/bin/linux/amd64/kubectl
    dest: /tmp/kubectl
    mode: '0755'

- name: Move kubectl to /usr/local/bin
 command:
    cmd: mv /tmp/kubectl /usr/local/bin/kubectl
