- name: Download KinD binary
  get_url:
    url: https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
    dest: /usr/local/bin/kind
    mode: '0755'

- name: Create KinD cluster
  command: >
    kind create cluster --name hero --config {{ role_path }}/files/config-multi-node.yaml